<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-CJN9AFV" failures="1" tests="5" name="Test" time="55.973" errors="0" timestamp="2025-10-04T20:06:22 IST">
  <testcase classname="com.thetestingacademy.tests.vwo.pageObjectModelTC.TestVWOLogin_05_TakeScreen_Retry_Prop_Improved_POM" name="testFail" time="8.7">
    <skipped/>
  </testcase> <!-- testFail -->
  <testcase classname="com.thetestingacademy.tests.vwo.pageObjectModelTC.TestVWOLogin_05_TakeScreen_Retry_Prop_Improved_POM" name="testFail" time="9.485">
    <skipped/>
  </testcase> <!-- testFail -->
  <testcase classname="com.thetestingacademy.tests.vwo.pageObjectModelTC.TestVWOLogin_05_TakeScreen_Retry_Prop_Improved_POM" name="testFail" time="8.55">
    <skipped/>
  </testcase> <!-- testFail -->
  <testcase classname="com.thetestingacademy.tests.vwo.pageObjectModelTC.TestVWOLogin_05_TakeScreen_Retry_Prop_Improved_POM" name="testFail" time="9.762">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.thetestingacademy.tests.vwo.pageObjectModelTC.TestVWOLogin_05_TakeScreen_Retry_Prop_Improved_POM.testFail(TestVWOLogin_05_TakeScreen_Retry_Prop_Improved_POM.java:45)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testFail -->
  <testcase classname="com.thetestingacademy.tests.vwo.pageObjectModelTC.TestVWOLogin_05_TakeScreen_Retry_Prop_Improved_POM" name="testPass" time="7.365"/>
</testsuite> <!-- Test -->
